################################
## Airflow Pod Listing Role Binding
#################################
{{- if and .Values.rbacEnabled .Values.allowPodLaunching }}
{{- $grantWebserver := (eq .Values.executor "KubernetesExecutor")  }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-pod-listing-rolebinding
  labels:
    tier: airflow
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-pod-listing-role
subjects:
{{- if $grantWebserver }}
  - kind: ServiceAccount
    name: {{ .Release.Name }}-webserver-serviceaccount
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
