################################
## Airflow Pod Listing Role
#################################
{{- if and .Values.rbacEnabled .Values.allowPodLaunching }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-pod-listing-role
  labels:
    tier: airflow
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - "list"
      - "get"
  - apiGroups:
      - ""
    resources:
      - "pods/log"
    verbs:
      - "get"
{{- end }}
